version: '3.7'
services:
  web:
    image: ruby:3.1
    command: ruby app.rb
    working_dir: /app
    ports:
      - "4567:4567"
    volumes:
      - ".:/app"
      - bundler_gems:/usr/local/bundle/
    environment:
      - PUSHER_APP_ID=<YOUR_APP_ID>
      - PUSHER_KEY=<YOUR_PUSHER_KEY>
      - PUSHER_SECRET=<YOUR_PUSHER_SECRET>
      - PUSHER_CLUSTER=<YOUR_PUSHER_CLUSTER>
volumes:
  bundler_gems: